# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-17 13:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TicTacToe', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='move',
            name='x',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='move',
            name='y',
            field=models.IntegerField(null=True),
        ),
    ]
